// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NykantAPI.Data;

namespace NykantAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211215144948_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NykantAPI.Models.BagItem", b =>
                {
                    b.Property<string>("Subject")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Subject", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BagItems");
                });

            modelBuilder.Entity("NykantAPI.Models.BillingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("BillingAddress");
                });

            modelBuilder.Entity("NykantAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgSource")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgSource = "../images/Products/NYKANT_rack_naturolie_02.png",
                            Name = "Tøjstativer"
                        },
                        new
                        {
                            Id = 2,
                            ImgSource = "../images/Products/NYKANT_bord_naturolie_02.png",
                            Name = "Borde"
                        },
                        new
                        {
                            Id = 3,
                            ImgSource = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            Name = "Hylder"
                        },
                        new
                        {
                            Id = 4,
                            ImgSource = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_03.png",
                            Name = "Bænke"
                        },
                        new
                        {
                            Id = 5,
                            ImgSource = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            Name = "Bøjler"
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgSrc = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            ProductId = 1,
                            ProductSourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImgSrc = "../images/Products/NYKANT_boejle_sortolie_01.png",
                            ProductId = 1,
                            ProductSourceId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImgSrc = "../images/Products/NYKANT_boejle_hvidolie_01.png",
                            ProductId = 1,
                            ProductSourceId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImgSrc = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            ProductId = 2,
                            ProductSourceId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImgSrc = "../images/Products/NYKANT_boejle_sortolie_01.png",
                            ProductId = 2,
                            ProductSourceId = 2
                        },
                        new
                        {
                            Id = 6,
                            ImgSrc = "../images/Products/NYKANT_boejle_hvidolie_01.png",
                            ProductId = 2,
                            ProductSourceId = 3
                        },
                        new
                        {
                            Id = 7,
                            ImgSrc = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            ProductId = 3,
                            ProductSourceId = 1
                        },
                        new
                        {
                            Id = 8,
                            ImgSrc = "../images/Products/NYKANT_boejle_sortolie_01.png",
                            ProductId = 3,
                            ProductSourceId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImgSrc = "../images/Products/NYKANT_boejle_hvidolie_01.png",
                            ProductId = 3,
                            ProductSourceId = 3
                        },
                        new
                        {
                            Id = 10,
                            ImgSrc = "../images/Products/NYKANT_hylde_hvidolie_01.png",
                            ProductId = 4,
                            ProductSourceId = 4
                        },
                        new
                        {
                            Id = 11,
                            ImgSrc = "../images/Products/NYKANT_hylde_sortolie_01.png",
                            ProductId = 4,
                            ProductSourceId = 5
                        },
                        new
                        {
                            Id = 12,
                            ImgSrc = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            ProductId = 4,
                            ProductSourceId = 6
                        },
                        new
                        {
                            Id = 13,
                            ImgSrc = "../images/Products/NYKANT_hylde_hvidolie_01.png",
                            ProductId = 5,
                            ProductSourceId = 4
                        },
                        new
                        {
                            Id = 14,
                            ImgSrc = "../images/Products/NYKANT_hylde_sortolie_01.png",
                            ProductId = 5,
                            ProductSourceId = 5
                        },
                        new
                        {
                            Id = 15,
                            ImgSrc = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            ProductId = 5,
                            ProductSourceId = 6
                        },
                        new
                        {
                            Id = 16,
                            ImgSrc = "../images/Products/NYKANT_hylde_hvidolie_01.png",
                            ProductId = 6,
                            ProductSourceId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImgSrc = "../images/Products/NYKANT_hylde_sortolie_01.png",
                            ProductId = 6,
                            ProductSourceId = 5
                        },
                        new
                        {
                            Id = 18,
                            ImgSrc = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            ProductId = 6,
                            ProductSourceId = 6
                        },
                        new
                        {
                            Id = 19,
                            ImgSrc = "../images/Products/NYKANT_bord_naturolie_01.png",
                            ProductId = 7,
                            ProductSourceId = 7
                        },
                        new
                        {
                            Id = 20,
                            ImgSrc = "../images/Products/NYKANT_kortbaenk_naturolie_01.png",
                            ProductId = 8,
                            ProductSourceId = 8
                        },
                        new
                        {
                            Id = 21,
                            ImgSrc = "../images/Products/NYKANT_langbaenk_naturolie_01.png",
                            ProductId = 9,
                            ProductSourceId = 9
                        },
                        new
                        {
                            Id = 22,
                            ImgSrc = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_01.png",
                            ProductId = 10,
                            ProductSourceId = 10
                        },
                        new
                        {
                            Id = 23,
                            ImgSrc = "../images/Products/NYKANT_rack_naturolie_01.png",
                            ProductId = 11,
                            ProductSourceId = 11
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("NykantAPI.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 3,
                            Source = "../images/Products/NYKANT_boejle_hvidolie_01.png"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 3,
                            Source = "../images/Products/NYKANT_boejle_hvidolie_02.png"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            Source = "../images/Products/NYKANT_boejle_naturolie_01.png"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 1,
                            Source = "../images/Products/NYKANT_boejle_naturolie_02.png"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 2,
                            Source = "../images/Products/NYKANT_boejle_sortolie_01.png"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 2,
                            Source = "../images/Products/NYKANT_boejle_sortolie_02.png"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Source = "../images/Products/NYKANT_bord_naturolie_01.png"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 7,
                            Source = "../images/Products/NYKANT_bord_naturolie_02.png"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 7,
                            Source = "../images/Products/NYKANT_bord_naturolie_03.png"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 4,
                            Source = "../images/Products/NYKANT_hylde_hvidolie_01.png"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 4,
                            Source = "../images/Products/NYKANT_hylde_hvidolie_02.png"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 4,
                            Source = "../images/Products/NYKANT_hylde_hvidolie_03.png"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 6,
                            Source = "../images/Products/NYKANT_hylde_naturolie_01.png"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 6,
                            Source = "../images/Products/NYKANT_hylde_naturolie_02.png"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 6,
                            Source = "../images/Products/NYKANT_hylde_naturolie_03.png"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 5,
                            Source = "../images/Products/NYKANT_hylde_sortolie_01.png"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 5,
                            Source = "../images/Products/NYKANT_hylde_sortolie_02.png"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 5,
                            Source = "../images/Products/NYKANT_hylde_sortolie_03.png"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 8,
                            Source = "../images/Products/NYKANT_kortbaenk_naturolie_01.png"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 8,
                            Source = "../images/Products/NYKANT_kortbaenk_naturolie_02.png"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 8,
                            Source = "../images/Products/NYKANT_kortbaenk_naturolie_03.png"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 9,
                            Source = "../images/Products/NYKANT_langbaenk_naturolie_01.png"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 9,
                            Source = "../images/Products/NYKANT_langbaenk_naturolie_02.png"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 9,
                            Source = "../images/Products/NYKANT_langbaenk_naturolie_03.png"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_01.png"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_02.png"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_03.png"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_04.png"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_05.png"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_06.png"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_07.png"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_01.png"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_02.png"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_03.png"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_04.png"
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_05.png"
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_06.png"
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.NewsSub", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Email");

                    b.ToTable("NewsSubs");
                });

            modelBuilder.Entity("NykantAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentIntent_Id")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Taxes")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TotalPrice")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NykantAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("NykantAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageSource")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageSource2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Materials")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Note")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Number")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Oil")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Path")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Size")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Description = "Gertrud Description",
                            ImageSource = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_boejle_naturolie_02.png",
                            Materials = "Gertrud Materials",
                            Name = "Bøjlen Gertrud",
                            Note = "Gertrud Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_boejle_naturolie_01.png",
                            Price = 375.0,
                            Size = "Gertrud Size",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            Description = "Gertrud Description",
                            ImageSource = "../images/Products/NYKANT_boejle_sortolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_boejle_sortolie_02.png",
                            Materials = "Gertrud Materials",
                            Name = "Bøjlen Gertrud",
                            Note = "Gertrud Note",
                            Number = "101",
                            Oil = "Sortolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_boejle_sortolie_01.png",
                            Price = 375.0,
                            Size = "Gertrud Size",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Description = "Gertrud Description",
                            ImageSource = "../images/Products/NYKANT_boejle_hvidolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_boejle_hvidolie_02.png",
                            Materials = "Gertrud Materials",
                            Name = "Bøjlen Gertrud",
                            Note = "Gertrud Note",
                            Number = "101",
                            Oil = "Hvidolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_boejle_hvidolie_01.png",
                            Price = 375.0,
                            Size = "Gertrud Size",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Ingeborg Description",
                            ImageSource = "../images/Products/NYKANT_hylde_hvidolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_hylde_hvidolie_02.png",
                            Materials = "Ingeborg Materials",
                            Name = "Ingeborg Hylden",
                            Note = "Ingeborg Note",
                            Number = "101",
                            Oil = "Hvidolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_hylde_hvidolie_01.png",
                            Price = 595.0,
                            Size = "Ingeborg Size",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "Ingeborg Description",
                            ImageSource = "../images/Products/NYKANT_hylde_sortolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_hylde_sortolie_02.png",
                            Materials = "Ingeborg Materials",
                            Name = "Ingeborg Hylden",
                            Note = "Ingeborg Note",
                            Number = "101",
                            Oil = "Sortolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_hylde_sortolie_01.png",
                            Price = 595.0,
                            Size = "Ingeborg Size",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Ingeborg Description",
                            ImageSource = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_hylde_naturolie_02.png",
                            Materials = "Ingeborg Materials",
                            Name = "Ingeborg Hylden",
                            Note = "Ingeborg Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_hylde_naturolie_01.png",
                            Price = 595.0,
                            Size = "Ingeborg Size",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Dagmar Description",
                            ImageSource = "../images/Products/NYKANT_bord_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_bord_naturolie_02.png",
                            Materials = "Dagmar Materials",
                            Name = "Dagmar Bordet",
                            Note = "Dagmar Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_bord_naturolie_01.png",
                            Price = 2995.0,
                            Size = "Dagmar Size",
                            WeightInKg = 22.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Thyra Description",
                            ImageSource = "../images/Products/NYKANT_kortbaenk_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_kortbaenk_naturolie_02.png",
                            Materials = "Thyra Materials",
                            Name = "Thyra Kortbænken",
                            Note = "Thyra Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_kortbaenk_naturolie_01.png",
                            Price = 2985.0,
                            Size = "Thyra Size",
                            WeightInKg = 14.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Thyra Description",
                            ImageSource = "../images/Products/NYKANT_langbaenk_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_langbaenk_naturolie_02.png",
                            Materials = "Thyra Materials",
                            Name = "Thyra Langbænken",
                            Note = "Thyra Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_langbaenk_naturolie_01.png",
                            Price = 3885.0,
                            Size = "Thyra Size",
                            WeightInKg = 20.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Filippa Description",
                            ImageSource = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_02.png",
                            Materials = "Filippa Materials",
                            Name = "Filippa Bænk",
                            Note = "Filippa Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_opbevaringsbaenk_naturolie_01.png",
                            Price = 4395.0,
                            Size = "Filippa Size",
                            WeightInKg = 24.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Nora Description",
                            ImageSource = "../images/Products/NYKANT_rack_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_rack_naturolie_02.png",
                            Materials = "Nora Materials",
                            Name = "Nora Tøjstativ",
                            Note = "Nora Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_rack_naturolie_01.png",
                            Price = 2295.0,
                            Size = "Nora Size",
                            WeightInKg = 13.4
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("NykantAPI.Models.ShippingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("SameAsBilling")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("ShippingAddress");
                });

            modelBuilder.Entity("NykantAPI.Models.ShippingDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("ShippingDeliveries");
                });

            modelBuilder.Entity("NykantMVC.Models.ParcelshopData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CountryCodeISO3166A2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("DistanceMetersAsTheCrowFlies")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Longitude")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Number")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("ShippingDeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Streetname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Streetname2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ZipCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ShippingDeliveryId")
                        .IsUnique();

                    b.ToTable("ParcelshopData");
                });

            modelBuilder.Entity("NykantAPI.Models.BagItem", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.BillingAddress", b =>
                {
                    b.HasOne("NykantAPI.Models.Customer", "Customer")
                        .WithOne("BillingAddress")
                        .HasForeignKey("NykantAPI.Models.BillingAddress", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Color", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Image", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Order", b =>
                {
                    b.HasOne("NykantAPI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.OrderItem", b =>
                {
                    b.HasOne("NykantAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Product", b =>
                {
                    b.HasOne("NykantAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Review", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.ShippingAddress", b =>
                {
                    b.HasOne("NykantAPI.Models.Customer", "Customer")
                        .WithOne("ShippingAddress")
                        .HasForeignKey("NykantAPI.Models.ShippingAddress", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.ShippingDelivery", b =>
                {
                    b.HasOne("NykantAPI.Models.Order", "Order")
                        .WithOne("ShippingDelivery")
                        .HasForeignKey("NykantAPI.Models.ShippingDelivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantMVC.Models.ParcelshopData", b =>
                {
                    b.HasOne("NykantAPI.Models.ShippingDelivery", "ShippingDelivery")
                        .WithOne("ParcelshopData")
                        .HasForeignKey("NykantMVC.Models.ParcelshopData", "ShippingDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
