// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NykantAPI.Data;

namespace NykantAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NykantAPI.Models.BagItem", b =>
                {
                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Subject", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("BagItems");
                });

            modelBuilder.Entity("NykantAPI.Models.BillingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("BillingAddress");
                });

            modelBuilder.Entity("NykantAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImgSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgSource = "../images/Products/NYKANT_rack_naturolie_02.png",
                            Name = "Tøjstativer"
                        },
                        new
                        {
                            Id = 2,
                            ImgSource = "../images/Products/NYKANT_bord_naturolie_02.png",
                            Name = "Borde"
                        },
                        new
                        {
                            Id = 3,
                            ImgSource = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            Name = "Hylder"
                        },
                        new
                        {
                            Id = 4,
                            ImgSource = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_03.png",
                            Name = "Bænke"
                        },
                        new
                        {
                            Id = 5,
                            ImgSource = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            Name = "Bøjler"
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EColor")
                        .HasColumnType("int");

                    b.Property<string>("ImgSrc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            ProductId = 1,
                            ProductSourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            EColor = 2,
                            ImgSrc = "../images/Products/NYKANT_boejle_sortolie_01.png",
                            ProductId = 1,
                            ProductSourceId = 2
                        },
                        new
                        {
                            Id = 3,
                            EColor = 1,
                            ImgSrc = "../images/Products/NYKANT_boejle_hvidolie_01.png",
                            ProductId = 1,
                            ProductSourceId = 3
                        },
                        new
                        {
                            Id = 4,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            ProductId = 2,
                            ProductSourceId = 1
                        },
                        new
                        {
                            Id = 5,
                            EColor = 2,
                            ImgSrc = "../images/Products/NYKANT_boejle_sortolie_01.png",
                            ProductId = 2,
                            ProductSourceId = 2
                        },
                        new
                        {
                            Id = 6,
                            EColor = 1,
                            ImgSrc = "../images/Products/NYKANT_boejle_hvidolie_01.png",
                            ProductId = 2,
                            ProductSourceId = 3
                        },
                        new
                        {
                            Id = 7,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            ProductId = 3,
                            ProductSourceId = 1
                        },
                        new
                        {
                            Id = 8,
                            EColor = 2,
                            ImgSrc = "../images/Products/NYKANT_boejle_sortolie_01.png",
                            ProductId = 3,
                            ProductSourceId = 2
                        },
                        new
                        {
                            Id = 9,
                            EColor = 1,
                            ImgSrc = "../images/Products/NYKANT_boejle_hvidolie_01.png",
                            ProductId = 3,
                            ProductSourceId = 3
                        },
                        new
                        {
                            Id = 10,
                            EColor = 1,
                            ImgSrc = "../images/Products/NYKANT_hylde_hvidolie_01.png",
                            ProductId = 4,
                            ProductSourceId = 4
                        },
                        new
                        {
                            Id = 11,
                            EColor = 2,
                            ImgSrc = "../images/Products/NYKANT_hylde_sortolie_01.png",
                            ProductId = 4,
                            ProductSourceId = 5
                        },
                        new
                        {
                            Id = 12,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            ProductId = 4,
                            ProductSourceId = 6
                        },
                        new
                        {
                            Id = 13,
                            EColor = 1,
                            ImgSrc = "../images/Products/NYKANT_hylde_hvidolie_01.png",
                            ProductId = 5,
                            ProductSourceId = 4
                        },
                        new
                        {
                            Id = 14,
                            EColor = 2,
                            ImgSrc = "../images/Products/NYKANT_hylde_sortolie_01.png",
                            ProductId = 5,
                            ProductSourceId = 5
                        },
                        new
                        {
                            Id = 15,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            ProductId = 5,
                            ProductSourceId = 6
                        },
                        new
                        {
                            Id = 16,
                            EColor = 1,
                            ImgSrc = "../images/Products/NYKANT_hylde_hvidolie_01.png",
                            ProductId = 6,
                            ProductSourceId = 4
                        },
                        new
                        {
                            Id = 17,
                            EColor = 2,
                            ImgSrc = "../images/Products/NYKANT_hylde_sortolie_01.png",
                            ProductId = 6,
                            ProductSourceId = 5
                        },
                        new
                        {
                            Id = 18,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            ProductId = 6,
                            ProductSourceId = 6
                        },
                        new
                        {
                            Id = 19,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_bord_naturolie_01.png",
                            ProductId = 7,
                            ProductSourceId = 7
                        },
                        new
                        {
                            Id = 20,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_kortbaenk_naturolie_01.png",
                            ProductId = 8,
                            ProductSourceId = 8
                        },
                        new
                        {
                            Id = 21,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_langbaenk_naturolie_01.png",
                            ProductId = 9,
                            ProductSourceId = 9
                        },
                        new
                        {
                            Id = 22,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_01.png",
                            ProductId = 10,
                            ProductSourceId = 10
                        },
                        new
                        {
                            Id = 23,
                            EColor = 0,
                            ImgSrc = "../images/Products/NYKANT_rack_naturolie_01.png",
                            ProductId = 11,
                            ProductSourceId = 11
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.Cookie", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type1")
                        .HasColumnType("int");

                    b.Property<int>("Type2")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.ToTable("Cookies");

                    b.HasData(
                        new
                        {
                            Name = "Culture",
                            Category = 1,
                            Description = "Denne cookie gemmer din præference for sprog.",
                            Type1 = 1,
                            Type2 = 0
                        },
                        new
                        {
                            Name = "AntiforgeryToken",
                            Category = 0,
                            Description = "Denne cookie beskytter imod Cross-Site Request Forgery angreb",
                            Type1 = 0,
                            Type2 = 0
                        },
                        new
                        {
                            Name = "Session",
                            Category = 0,
                            Description = "Denne cookie husker/gemmer hvad du har lagt i din kurv, samt giver dig en bedre checkout oplevelse.",
                            Type1 = 0,
                            Type2 = 0
                        },
                        new
                        {
                            Name = "__stripe_mid",
                            Category = 0,
                            Description = "Denne cookie bruges af Stripe og sørger for at vores betalingsservice virker, og er sikker.",
                            Type1 = 1,
                            Type2 = 1
                        },
                        new
                        {
                            Name = "__stripe_sid",
                            Category = 0,
                            Description = "Denne cookie bruges af Stripe og sørger for at vores betalingsservice virker, og er sikker.",
                            Type1 = 1,
                            Type2 = 1
                        },
                        new
                        {
                            Name = "_ga",
                            Category = 3,
                            Description = "Denne cookie bruges af Google Analytics og registrere et unikt ID, som bliver brugt til at generere statistiske data om hvordan besøgende bruger hjemmesiden.",
                            Type1 = 1,
                            Type2 = 1
                        },
                        new
                        {
                            Name = "_ga_2LWYP6ZC27",
                            Category = 3,
                            Description = "Denne cookie bruges af Google Analytics og indsamler data så som hvor mange gange en bruger har besøgt siden, datoen de har besøgt og det seneste besøg.",
                            Type1 = 1,
                            Type2 = 1
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("NykantAPI.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 3,
                            Source = "../images/Products/NYKANT_boejle_hvidolie_01.png"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 3,
                            Source = "../images/Products/NYKANT_boejle_hvidolie_02.png"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 1,
                            Source = "../images/Products/NYKANT_boejle_naturolie_01.png"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 1,
                            Source = "../images/Products/NYKANT_boejle_naturolie_02.png"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 2,
                            Source = "../images/Products/NYKANT_boejle_sortolie_01.png"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 2,
                            Source = "../images/Products/NYKANT_boejle_sortolie_02.png"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Source = "../images/Products/NYKANT_bord_naturolie_01.png"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 7,
                            Source = "../images/Products/NYKANT_bord_naturolie_02.png"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 7,
                            Source = "../images/Products/NYKANT_bord_naturolie_03.png"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 4,
                            Source = "../images/Products/NYKANT_hylde_hvidolie_01.png"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 4,
                            Source = "../images/Products/NYKANT_hylde_hvidolie_02.png"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 4,
                            Source = "../images/Products/NYKANT_hylde_hvidolie_03.png"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 6,
                            Source = "../images/Products/NYKANT_hylde_naturolie_01.png"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 6,
                            Source = "../images/Products/NYKANT_hylde_naturolie_02.png"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 6,
                            Source = "../images/Products/NYKANT_hylde_naturolie_03.png"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 5,
                            Source = "../images/Products/NYKANT_hylde_sortolie_01.png"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 5,
                            Source = "../images/Products/NYKANT_hylde_sortolie_02.png"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 5,
                            Source = "../images/Products/NYKANT_hylde_sortolie_03.png"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 8,
                            Source = "../images/Products/NYKANT_kortbaenk_naturolie_01.png"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 8,
                            Source = "../images/Products/NYKANT_kortbaenk_naturolie_02.png"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 8,
                            Source = "../images/Products/NYKANT_kortbaenk_naturolie_03.png"
                        },
                        new
                        {
                            Id = 22,
                            ProductId = 9,
                            Source = "../images/Products/NYKANT_langbaenk_naturolie_01.png"
                        },
                        new
                        {
                            Id = 23,
                            ProductId = 9,
                            Source = "../images/Products/NYKANT_langbaenk_naturolie_02.png"
                        },
                        new
                        {
                            Id = 24,
                            ProductId = 9,
                            Source = "../images/Products/NYKANT_langbaenk_naturolie_03.png"
                        },
                        new
                        {
                            Id = 25,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_01.png"
                        },
                        new
                        {
                            Id = 26,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_02.png"
                        },
                        new
                        {
                            Id = 27,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_03.png"
                        },
                        new
                        {
                            Id = 28,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_04.png"
                        },
                        new
                        {
                            Id = 29,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_05.png"
                        },
                        new
                        {
                            Id = 30,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_06.png"
                        },
                        new
                        {
                            Id = 31,
                            ProductId = 10,
                            Source = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_07.png"
                        },
                        new
                        {
                            Id = 32,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_01.png"
                        },
                        new
                        {
                            Id = 33,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_02.png"
                        },
                        new
                        {
                            Id = 34,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_03.png"
                        },
                        new
                        {
                            Id = 35,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_04.png"
                        },
                        new
                        {
                            Id = 36,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_05.png"
                        },
                        new
                        {
                            Id = 37,
                            ProductId = 11,
                            Source = "../images/Products/NYKANT_rack_naturolie_06.png"
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("NykantAPI.Models.NewsSub", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Email");

                    b.ToTable("NewsSubs");
                });

            modelBuilder.Entity("NykantAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EstimatedDelivery")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentIntent_Id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxLessPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taxes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NykantAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("NykantAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("AssemblyPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EColor")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedDelivery")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageSource2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Materials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Package")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pieces")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("WeightInKg")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 0,
                            AssemblyPath = "none",
                            CategoryId = 5,
                            Description = "Gertrud Description",
                            EColor = 0,
                            ExpectedDelivery = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_boejle_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_boejle_naturolie_02.png",
                            Materials = "Gertrud Materials",
                            Name = "Bøjlen Gertrud / 3 stk.",
                            Note = "Gertrud Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Package = "Gertrud Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_boejle_naturolie_01.png",
                            Pieces = 3,
                            Price = 375.0,
                            Size = "Gertrud Size",
                            Title = "Bøjle i massivt egetræ - Behandlet med naturolie",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0,
                            AssemblyPath = "none",
                            CategoryId = 5,
                            Description = "Gertrud Description",
                            EColor = 2,
                            ExpectedDelivery = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_boejle_sortolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_boejle_sortolie_02.png",
                            Materials = "Gertrud Materials",
                            Name = "Bøjlen Gertrud / 3 stk.",
                            Note = "Gertrud Note",
                            Number = "101",
                            Oil = "Sortolie",
                            Package = "Gertrud Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_boejle_sortolie_01.png",
                            Pieces = 3,
                            Price = 375.0,
                            Size = "Gertrud Size",
                            Title = "Bøjle i massivt egetræ - Behandlet med sortolie",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 3,
                            Amount = 0,
                            AssemblyPath = "none",
                            CategoryId = 5,
                            Description = "Gertrud Description",
                            EColor = 1,
                            ExpectedDelivery = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_boejle_hvidolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_boejle_hvidolie_02.png",
                            Materials = "Gertrud Materials",
                            Name = "Bøjlen Gertrud / 3 stk.",
                            Note = "Gertrud Note",
                            Number = "101",
                            Oil = "Hvidolie",
                            Package = "Gertrud Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_boejle_hvidolie_01.png",
                            Pieces = 3,
                            Price = 375.0,
                            Size = "Gertrud Size",
                            Title = "Bøjle i massivt egetræ - Behandlet med hvidolie",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 4,
                            Amount = 0,
                            AssemblyPath = "/word/Hylde_Vejledning.docx",
                            CategoryId = 3,
                            Description = "Ingeborg Description",
                            EColor = 1,
                            ExpectedDelivery = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_hylde_hvidolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_hylde_hvidolie_02.png",
                            Length = "600 mm.",
                            Materials = "Ingeborg Materials",
                            Name = "Ingeborg Hylden",
                            Note = "Ingeborg Note",
                            Number = "101",
                            Oil = "Hvidolie",
                            Package = "Ingeborg Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_hylde_hvidolie_01.png",
                            Pieces = 1,
                            Price = 595.0,
                            Size = "Ingeborg Size",
                            Title = "Hylde i massivt egetræ - Behandlet med hvidolie",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 5,
                            Amount = 0,
                            AssemblyPath = "/word/Hylde_Vejledning.docx",
                            CategoryId = 3,
                            Description = "Ingeborg Description",
                            EColor = 2,
                            ExpectedDelivery = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_hylde_sortolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_hylde_sortolie_02.png",
                            Length = "600 mm.",
                            Materials = "Ingeborg Materials",
                            Name = "Ingeborg Hylden",
                            Note = "Ingeborg Note",
                            Number = "101",
                            Oil = "Sortolie",
                            Package = "Ingeborg Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_hylde_sortolie_01.png",
                            Pieces = 1,
                            Price = 595.0,
                            Size = "Ingeborg Size",
                            Title = "Hylde i massivt egetræ - Behandlet med sortolie",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 6,
                            Amount = 0,
                            AssemblyPath = "/word/Hylde_Vejledning.docx",
                            CategoryId = 3,
                            Description = "Ingeborg Description",
                            EColor = 0,
                            ExpectedDelivery = new DateTime(2022, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_hylde_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_hylde_naturolie_02.png",
                            Length = "600 mm.",
                            Materials = "Ingeborg Materials",
                            Name = "Ingeborg Hylden",
                            Note = "Ingeborg Note",
                            Number = "101",
                            Oil = "Naturolie",
                            Package = "Ingeborg Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_hylde_naturolie_01.png",
                            Pieces = 1,
                            Price = 595.0,
                            Size = "Ingeborg Size",
                            Title = "Hylde i massivt egetræ - Behandlet med naturolie",
                            WeightInKg = 11.6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 72,
                            AssemblyPath = "/word/Bord.docx",
                            CategoryId = 2,
                            Description = "Dagmar Description",
                            EColor = 0,
                            ExpectedDelivery = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_bord_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_bord_naturolie_02.png",
                            Materials = "Dagmar Materials",
                            Name = "Dagmar Bordet",
                            Note = "Dagmar Note",
                            Number = "16001",
                            Oil = "Naturolie",
                            Package = "Dagmar Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_bord_naturolie_01.png",
                            Pieces = 1,
                            Price = 2995.0,
                            Size = "Dagmar Size",
                            Title = "Bord i massivt egetræ - Behandlet med naturolie",
                            WeightInKg = 22.0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 42,
                            AssemblyPath = "/word/bænk.docx",
                            CategoryId = 4,
                            Description = "Thyra Short Description",
                            EColor = 0,
                            ExpectedDelivery = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_kortbaenk_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_kortbaenk_naturolie_02.png",
                            Length = "1150 mm.",
                            Materials = "Thyra Short Materials",
                            Name = "Thyra Bænken",
                            Note = "Thyra Short Note",
                            Number = "12001",
                            Oil = "Naturolie",
                            Package = "Thyra Short Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_kortbaenk_naturolie_01.png",
                            Pieces = 1,
                            Price = 2985.0,
                            Size = "Thyra Short Size",
                            Title = "Bænk i massivt egetræ - Behandlet med naturolie",
                            WeightInKg = 14.0
                        },
                        new
                        {
                            Id = 9,
                            Amount = 17,
                            AssemblyPath = "/word/bænk.docx",
                            CategoryId = 4,
                            Description = "Thyra Description",
                            EColor = 0,
                            ExpectedDelivery = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_langbaenk_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_langbaenk_naturolie_02.png",
                            Length = "1700 mm.",
                            Materials = "Thyra Materials",
                            Name = "Thyra Bænken",
                            Note = "Thyra Note",
                            Number = "11001",
                            Oil = "Naturolie",
                            Package = "Thyra Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_langbaenk_naturolie_01.png",
                            Pieces = 1,
                            Price = 3885.0,
                            Size = "Thyra Size",
                            Title = "Bænk i massivt egetræ - Behandlet med naturolie",
                            WeightInKg = 20.0
                        },
                        new
                        {
                            Id = 10,
                            Amount = 50,
                            AssemblyPath = "none",
                            CategoryId = 4,
                            Description = "Filippa Description",
                            EColor = 0,
                            ExpectedDelivery = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_opbevaringsbaenk_naturolie_02.png",
                            Materials = "Filippa Materials",
                            Name = "Filippa Bænk",
                            Note = "Filippa Note",
                            Number = "10001",
                            Oil = "Naturolie",
                            Package = "Filippa Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_opbevaringsbaenk_naturolie_01.png",
                            Pieces = 1,
                            Price = 4395.0,
                            Size = "Filippa Size",
                            Title = "Opbevaringsbænk i massivt egetræ - Behandlet med naturolie",
                            WeightInKg = 24.0
                        },
                        new
                        {
                            Id = 11,
                            Amount = 26,
                            AssemblyPath = "/word/Tøjstativ.docx",
                            CategoryId = 1,
                            Description = "Nora Description",
                            EColor = 0,
                            ExpectedDelivery = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageSource = "../images/Products/NYKANT_rack_naturolie_01.png",
                            ImageSource2 = "../images/Products/NYKANT_rack_naturolie_02.png",
                            Materials = "Nora Materials",
                            Name = "Nora Tøjstativ",
                            Note = "Nora Note",
                            Number = "13001 + 13001A",
                            Oil = "Naturolie",
                            Package = "Nora Package",
                            Path = "C:/Users/Christian/Documents/GitHub/Nykant/NykantMVC/wwwroot/images/Products/NYKANT_rack_naturolie_01.png",
                            Pieces = 1,
                            Price = 2295.0,
                            Size = "Nora Size",
                            Title = "Tøjstativ i massivt egetræ - Behandlet med naturolie",
                            WeightInKg = 8.0
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.ProductLength", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductReferenceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductLength");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Length = "1150 mm.",
                            ProductId = 8,
                            ProductReferenceId = 8
                        },
                        new
                        {
                            Id = 2,
                            Length = "1700 mm.",
                            ProductId = 8,
                            ProductReferenceId = 9
                        },
                        new
                        {
                            Id = 3,
                            Length = "1150 mm.",
                            ProductId = 9,
                            ProductReferenceId = 8
                        },
                        new
                        {
                            Id = 4,
                            Length = "1700 mm.",
                            ProductId = 9,
                            ProductReferenceId = 9
                        },
                        new
                        {
                            Id = 5,
                            Length = "400 mm.",
                            ProductId = 4,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 6,
                            Length = "600 mm.",
                            ProductId = 4,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 7,
                            Length = "800 mm.",
                            ProductId = 4,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 8,
                            Length = "1000 mm.",
                            ProductId = 4,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 9,
                            Length = "400 mm.",
                            ProductId = 5,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 10,
                            Length = "600 mm.",
                            ProductId = 5,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 11,
                            Length = "800 mm.",
                            ProductId = 5,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 12,
                            Length = "1000 mm.",
                            ProductId = 5,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 13,
                            Length = "400 mm.",
                            ProductId = 6,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 14,
                            Length = "600 mm.",
                            ProductId = 6,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 15,
                            Length = "800 mm.",
                            ProductId = 6,
                            ProductReferenceId = 6
                        },
                        new
                        {
                            Id = 16,
                            Length = "1000 mm.",
                            ProductId = 6,
                            ProductReferenceId = 6
                        });
                });

            modelBuilder.Entity("NykantAPI.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("NykantAPI.Models.ShippingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SameAsBilling")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("ShippingAddress");
                });

            modelBuilder.Entity("NykantAPI.Models.ShippingDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("ShippingDeliveries");
                });

            modelBuilder.Entity("NykantMVC.Models.ParcelshopData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCodeISO3166A2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistanceMetersAsTheCrowFlies")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShippingDeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Streetname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Streetname2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingDeliveryId")
                        .IsUnique();

                    b.ToTable("ParcelshopData");
                });

            modelBuilder.Entity("NykantAPI.Models.BagItem", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.BillingAddress", b =>
                {
                    b.HasOne("NykantAPI.Models.Customer", "Customer")
                        .WithOne("BillingAddress")
                        .HasForeignKey("NykantAPI.Models.BillingAddress", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Color", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Image", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Invoice", b =>
                {
                    b.HasOne("NykantAPI.Models.Order", "Order")
                        .WithOne("Invoice")
                        .HasForeignKey("NykantAPI.Models.Invoice", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Order", b =>
                {
                    b.HasOne("NykantAPI.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.OrderItem", b =>
                {
                    b.HasOne("NykantAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Product", b =>
                {
                    b.HasOne("NykantAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.ProductLength", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany("ProductLengths")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.Review", b =>
                {
                    b.HasOne("NykantAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.ShippingAddress", b =>
                {
                    b.HasOne("NykantAPI.Models.Customer", "Customer")
                        .WithOne("ShippingAddress")
                        .HasForeignKey("NykantAPI.Models.ShippingAddress", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantAPI.Models.ShippingDelivery", b =>
                {
                    b.HasOne("NykantAPI.Models.Order", "Order")
                        .WithOne("ShippingDelivery")
                        .HasForeignKey("NykantAPI.Models.ShippingDelivery", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NykantMVC.Models.ParcelshopData", b =>
                {
                    b.HasOne("NykantAPI.Models.ShippingDelivery", "ShippingDelivery")
                        .WithOne("ParcelshopData")
                        .HasForeignKey("NykantMVC.Models.ParcelshopData", "ShippingDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
